src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use App\Repository\ArticleRepository;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    use TimestampableEntity;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Gedmo\Slug(fields={"title"})
     */
    private $slug;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $publishedAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $author;

    /**
     * @ORM\Column(type="integer")
     */
    private $likesCount = 0;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageFile;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="article", fetch="EXTRA_LAZY")
     * @ORM\OrderBy({"createdAt"="DESC"})
     */
    private $comments;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="articles")
     */
    private $tags;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(?\DateTimeInterface $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getLikesCount(): ?int
    {
        return $this->likesCount;
    }

    public function setLikesCount(int $likesCount): self
    {
        $this->likesCount = $likesCount;

        return $this;
    }

    public function getImageFile(): ?string
    {
        return $this->imageFile;
    }

    public function setImageFile(?string $imageFile): self
    {
        $this->imageFile = $imageFile;

        return $this;
    }

    public function getImagePath()
    {
        return 'images/' . $this->getImageFile();
    }

    public function incrementLikesCount(): self
    {
        $this->likesCount = $this->likesCount + 1;
        
        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getNonDeletedComments(): Collection
    {
        $criteria = ArticleRepository::createNonDeletedCriteria();

        return $this->comments->matching($criteria);
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }
}

src/Controller/ArticlesController.php
<?php

namespace App\Controller;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Psr\Log\LoggerInterface;
use App\Service\SlackClient;
use App\Repository\ArticleRepository;
use App\Entity\Article;
use Doctrine\ORM\EntityManagerInterface;

class ArticlesController extends AbstractController
{
    /**
     * @Route("/articles", name = "articles_index")
     */
    public function index(ArticleRepository $repository)
    {
        $articles = $repository->findPublishedArticlesOrderedByPublishedAt();

        return $this->render('articles/index.html.twig', [
            'articles' => $articles,
        ]);
    }

    /**
     * @Route("/articles/{slug}", name = "articles_show")
     */
    public function show(Article $article)
    {
        return $this->render('articles/show.html.twig', [
            'article' => $article,
        ]);
    }

    /**
     * @Route("/articles/{slug}/likes", name = "articles_toggle_likes", methods={"POST"})
     */
    public function toggleLikes(Article $article, LoggerInterface $logger, SlackClient $slack, EntityManagerInterface $em)
    {
        $article->incrementLikesCount();
        $em->flush();

        $slack->sendMessage('Mike Wazovzky', 'Your article has been liked.');

        $logger->info('Article has been liked.');

        return $this->json(['likes' => $article->getLikesCount()]);
    }
}

templates/articles/comment.html.twig
<div class="comment">
    <div>
        <img class="avatar" src="{{ asset('images/rendall.jpg') }}">
    </div>
    <div>
        <span class="comment-meta">
            <strong>{{ comment.authorName }} </strong> wrote <strong>{{ comment.createdAt|ago }}</strong>
        </span>
        {% if comment.isDeleted %}
            <span class="fas fa-times"></span> deleted
        {% endif %}
        <div>
            {{ comment.content }}
        </div>
        <a href="">Reply</a>
    </div>
</div>

templates/articles/comment_create.html.twig
<div class="comment-create">
    <div>
        <img class="avatar-lg" src="{{ asset('images/boo.jpg') }}">
        <span class="block"><strong>Boo</strong></span>     
    </div>
    <form>
        <div class="form-group">
            <textarea class="form-control" rows="4" placeholder="Enter your comment here"></textarea>
        </div>
        <div class="form-group right">
            <button class="btn btn-sm btn-primary">Post a comment</button> 
        </div>
    </form>
</div>

templates/articles/comments.html.twig
<hr>
<h2>Comments [{{ comments|length }}]</h2>

{% include 'articles/comment_create.html.twig' %}   

{% for comment in comments %}
    {% include 'articles/comment.html.twig' with { comment: comment } %}
{% endfor %}

templates/articles/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Articles
{% endblock %}

{% block body %}
<div class="container">
    <h1>Article index</h1>
    {% for article in articles %}
        <div class="flex">
            <div>
               <img class="article-image-thumbnail" src="{{ asset(article.imagePath) }}">
            </div>
            <div class="article-summary">
                <h2 class="article-summary-header">
                    <a href="{{ path('articles_show', { slug: article.slug }) }}">
                        {{ article.title }}
                    </a>
                </h2>
                <small>{% include 'articles/tags.html.twig' with { tags: article.tags } %}</small>
                <div class="article-meta">
                    published: <strong>{{ article.publishedAt ? article.publishedAt|ago }}</strong>
                    by: <strong>{{ article.author }}</strong>, 
                    has <strong>{{ article.nonDeletedComments|length }}</strong> comment
                </div>
                <div>
                    {{ article.content|truncate(180)|markdown }}
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

templates/articles/show.html.twig
{% extends 'content_base.html.twig' %}

{% block title %}{{ article.title }}{% endblock %}

{% block content_body %}
    <div class="article-header">
        <div>
            <h1>{{ article.title }}</h1>
            <div>published: <strong>{{ article.publishedAt ? article.publishedAt|ago }}</strong></div>
            <div>by: <strong>{{ article.author }}</strong></div>
            {% include 'articles/tags.html.twig' with { tags: article.tags } %} 
        </div>
        <div>
            <span class="js-like-article-count">{{ article.likesCount }}</span> 
            <a href="{{ path('articles_toggle_likes', { slug: article.slug }) }}" class="far fa-heart js-like-article"></a>
        </div>
    </div>
    <div>
        <img class="article-image" src="{{ asset(article.imagePath) }}">
    </div>
    {{ article.content|cached_markdown }}
    {% include 'articles/comments.html.twig' with { comments: article.nonDeletedComments } %} 
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/articles_show.js') }}"></script>
{% endblock %}

templates/articles/tags.html.twig
{% for tag in tags %}
    <span class="badge badge-secondary">{{ tag.slug }}</span>
{% endfor %}